smpallen99/ex_admin

- README.md
I replaced `compile` with `deps.compile` in the README. This seemed to run both the `deps.get` and then `deps.compile` whereas simply running the original `mix do deps.get, compile` never ran the compile command and caused the issue in #14
> Update deps.compile mix command in README

- lib/ex_admin/breadcrumb.ex
- lib/ex_admin/ex_admin.ex
If a UUID was used as the primary key, the show action would fail with:
> ** (exit) an exception was raised:
> ** (ArgumentError) argument error
> :erlang.binary_to_integer("f7257870-bb73-4d88-b849-6aefd16ba986")
> lib/ex_admin/ex_admin.ex:177: ExAdmin.default_resource_title_actions/2
> lib/ex_admin/view_helpers.ex:88: ExAdmin.ViewHelpers.title_bar_right/1
> lib/ex_admin/view_helpers.ex:19: ExAdmin.ViewHelpers.title_bar/2
> web/templates/layout/admin.html.eex:30: ExAdmin.LayoutView."admin.html"/1
Since the id is converted to a string again in
`ExAdmin.Utils.get_route_path/3)` this conversation does not seem to be
required for integer ids.
> fix(ExAdmin): don't convert id to integer

- lib/ex_admin/form.ex
- lib/ex_admin/register.ex
- mix.exs
- mix.lock
There were several warnings being generated by the macros provided
ExActor which were fixed by upgrading the version.
Several unused variable warnings have also been fixed.
Previously the following code:
register_page("this will warn")
Would cause the following compiler warning:
> warning: this expression will fail with ArgumentError
This is no longer the case, `Kernel.to_string` is used to allow anything
that implements the String.Chars protocol to be used.
> fix(ExAdmin): compiler warnings

- README.md
- lib/mix/tasks/admin.install.ex
- web/router.ex
According to the principle of least astonishment I propose to use existing and already-known ways to configure admin routes.
``` elixir
defmodule MyProject.Router do
use MyProject.Web, :router
use ExAdmin.Router
...
scope "/", MyProject do
...
end
scope "/admin", ExAdmin do
pipe_through :browser
admin_routes
end
```
> Change including of admin routes to be more natural for Plug & Phoenix.

- lib/ex_admin/form.ex
- lib/ex_admin/params_to_atoms.ex
It allows to use `input[type="file"]` in admin forms. 
For example, for image uploading. Tested with https://github.com/stavro/arc_ecto
Fixes #33
> Added ability to use file upload in admin forms.

- mix.exs
- mix.lock
I've bumped version of scrivener to 1.0, because 0.10 was dependent on ecto < 1.0.0.
This was causing deps conflict such as:
```
Dependencies have diverged:
* ecto (Hex package)
the dependency ecto
> In deps/sqlite_ecto/mix.exs:
{:ecto, "~> 1.0", [optional: false, hex: :ecto, manager: :mix]}
does not match the requirement specified
> In deps/scrivener/mix.exs:
{:ecto, "~> 0.13.0", [optional: false, hex: :ecto]}
Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```
And solving this problem by overriding, is not good for user experience with ex_admin it self.
> bump version of scrivener

- lib/ex_admin/ex_admin.ex
- test/controller_test.exs
- test/support/conn_case.exs
- test/support/error_view.ex
- web/controllers/admin_controller.ex
There are several improvements:
0. Refactored method `get_registered_by_controller_route!/1` to `get_registered_by_controller_route!/2` with optional parameter `conn` to save compatibility
1. Refactored to use `get_registered_by_controller_route!/2` everywhere when possible
2. Refactored method `get_registered_by_controller_route!/2` to raise `Phoenix.Router.NoRouteError`
3. Refactored `:show`, `:update`, `:edit`, `destroy` to raise `Phoenix.Router.NoRouteError` when resource is not found
4. Added tests to cover the changes
> Made fixes to solve https://github.com/smpallen99/ex_admin/issues/74

- lib/mix/tasks/admin.gen.resource.ex
I'm pretty sure that we should stick to underscore file naming conventions while generating new resources. This should help.
> Change file naming in generator

- README.md
When using with git.
/priv/static is usually untracked.
To make it play nice with git we need to track /priv/static.
Thanks
Dev.
> track priv/static/themes

- priv/static/js/jquery-ujs.js.js
- priv/static/themes/active_admin/js/jquery-ujs.js.js
- priv/static/themes/admin_lte2/js/jquery-ujs.js.js
- web/templates/layout/active_admin.html.eex
- web/templates/layout/admin_lte2.html.eex
This is a simple patch that fixes a couple of issues with Safari: #98 #86
Add missing `]` to attribute selectors
Change `let` to `var`
> Fix some issues with Safari

- lib/ex_admin/table.ex
This fixes a bug where the following code whould not behave as expected:
```elixir
show account do
panel "Inventory" do
table_for account.inventory do
column "Asset", &__MODULE__.inventory_name/1
column "PO", &(&1.sales_order.po)
column :quantity
end
end
end
```
[this is taken from the docs](https://hexdocs.pm/ex_admin/ExAdmin.Show.html#table_for/3)
The problem happens because `ExAdmin.Register.column` puts the function inside the opts under the key `fun`. [see this](https://github.com/smpallen99/ex_admin/blob/v0.7.5/lib/ex_admin/register.ex#L645)
> fix column in table_for renders empty with func

- config/config.exs
- config/test.exs
- lib/ex_admin/breadcrumb.ex
- lib/ex_admin/filter.ex
- lib/ex_admin/form/fields.ex
- lib/ex_admin/gettext.ex
- lib/ex_admin/index.ex
- lib/ex_admin/paginate.ex
- lib/ex_admin/table.ex
- lib/ex_admin/themes/active_admin/filter.ex
- lib/ex_admin/themes/active_admin/form.ex
- lib/ex_admin/themes/active_admin/index.ex
- lib/ex_admin/themes/active_admin/table.ex
- lib/ex_admin/themes/admin_lte2/filter.ex
- lib/ex_admin/themes/admin_lte2/form.ex
- lib/ex_admin/themes/admin_lte2/index.ex
- lib/ex_admin/themes/admin_lte2/table.ex
- lib/ex_admin/utils.ex
- lib/ex_admin/view_helpers.ex
- lib/mix/tasks/admin.install.ex
- mix.exs
- priv/gettext/default.pot
- priv/gettext/fr_FR/LC_MESSAGES/default.po
- priv/templates/admin.install/dashboard.exs
- web/controllers/admin_association_controller.ex
- web/controllers/admin_resource_controller.ex
- web/templates/admin_resource/index.html.eex
- web/templates/themes/active_admin/layout/header.html.eex
- web/templates/themes/admin_lte2/layout/header.html.eex
In reference to #136, a  first attempt to bring i18n support, using Gettext.
Issues :
- No error messages translation (don't need those, in my case)
- No javascript strings translation (I don't know how to do this, perhaps generate the js files from Elixir so we could leverage Gettext ?)
- This a WIP, there could be some errors, some untranslated strings left...etc. ;-)
The .pot file is in priv/gettext, a french .po file is provided.
To test, add the following your app config.exs :
```
config :ex_admin, ExAdmin.Gettext,
default_locale: "fr_FR"
```
> I18n support

- lib/ex_admin/ex_admin.ex
- web/templates/layout/active_admin.html.eex
- web/templates/layout/admin_lte2.html.eex
* add example for including an actual script tag in the head
Originally I wanted to add another config to include custom scripts (like the head template) in order to not block site rendering. However as [Google](https://developers.google.com/speed/docs/insights/BlockingJS) is suggesting nowadays yuo should go back to put them into the head (for earlier parsing) and mark them as `async` (for making them non-blocking). 
TL;DR: Just removed the static `<script>` tag and `require` statement and added some docs
> Remove hardcoded scripts from layout

- lib/ex_admin/repo.ex
An error was thrown with admin_lte2 when using "has_many" in a form. `ExAdmin.Repo` would handle only `through` relations.
> Fix form has_many

- lib/mix/tasks/admin.install.ex
@smpallen99 There was a typo in the comments generated at the end of the brunch config file causing this problem.
This is a very small fix, hope this helps.
> Fix #218 CSS not found - typo in documentation

- lib/ex_admin/form.ex
- lib/ex_admin/themes/active_admin/form.ex
- lib/ex_admin/themes/admin_lte2/form.ex
With this feature you could specify hint for input inside `form` macro:
``` elixir
form client do
inputs do
input client, :description, hint: "Enter something descriptive"
end
end
```
to get something like that:
> Added support of hint option for form elements

- web/controllers/admin_resource_controller.ex
- web/ex_admin/resource_controller.ex
ACL rules could be based on the resource attributes, like 
`current_user.company_id == document.company_id`
So, `conn.assigns.resource` should be loaded before authorization check.
> Refactored authorization to perform check after resource loading

- lib/ex_admin/authentication.ex
- lib/ex_admin/ex_admin.ex
- lib/ex_admin/helpers.ex
- lib/ex_admin/index.ex
- lib/ex_admin/navigation.ex
- lib/ex_admin/utils.ex
- web/controllers/admin_resource_controller.ex
- web/ex_admin/resource_controller.ex
If possible dispatching by resource should be used to provide more precise information to ACL rules.
In cases when there is no resource (like ExAdmin.Dashboard) - fallback to dispatching by defn will be used.
> Dispatch ExAdmin.Authorization by resource instead of defn

- .travis.yml
- CONTRIBUTING.md
- config/config.exs
- config/test.exs
- lib/ex_admin.ex
- mix.exs
- mix.lock
- test/integration/create_test.exs
- test/integration/dashboard_test.exs
- test/integration/delete_test.exs
- test/integration/update_test.exs
- test/support/acceptance_case.exs
- test/support/web.exs
- test/test_helper.exs
Motivation:
- The admin generates a lot of custom html, forms and user
interactions. Setup end to end integration tests to make sure that
the user's experience is working as expected.
- smpallen99/ex_admin/issues/11
Changes:
- Setup Hound
- Setup Travis to work with phantomjs
- Turn on the server for the test environment and ensure cowboy is
running.
- Add new integration tests and required support files.
- As a first test just test the edit page and dashboard for an
example.
> Setting up hound integration tests

- web/ex_admin/resource_controller.ex
This is throwing an exception when custom changeset functions are specified. I vaguely remember adding the `required` array key to `ExAdmin.Changeset`, and all tests pass for me with this change.
Thanks, Steve!
> Fetch required fields from the changeset itself

- web/templates/admin_resource/index.html.eex
Am seeing escaped html in my admin and noticed this missing quoted class attribute. Not sure if this is used but very minor change.
> Fix class attribute quoting

- lib/ex_admin/helpers.ex
- lib/ex_admin/table.ex
- test/helpers_test.exs
When given a `:map` structure that elixir's default implementation `to_string` can't handle, ex_admin would fail as well because the custom protocol was not being used
As a test case, you can see that the previous version failed to render
a model such as this:
```
%User{data: %{a_complex_list: [%{}]}
```
This would fail because `to_string([%{}])` also fails (you can easily
try that on an elixir console)
I also added a test that would fail with the previous version
This PR solves it by using the custom `ExAdmin.Render.to_string`
protocol instead.
> Fixes rendering of complex maps

- lib/ex_admin/index.ex
Before this change, the index macro was generating these warnings when
used:
lib/ex_admin/index.ex:149: The variable _@48 can never match since
previous clauses completely covered the type 'nil'
lib/ex_admin/index.ex:149: The variable _@18 can never match since
previous clauses completely covered the type 'nil'
The call to unquote(contents) could change the value of that variable,
but dialyzer isn't smart enough to realize that.
> Fix dialyzer no_match warning

- web/ex_admin/resource_controller.ex
When using this macro, you would get this warning:
> warning: this check/guard will always yield the same result
Fixes https://github.com/smpallen99/ex_admin/issues/304
> Fix resource_controller macro compiler warning

- lib/ex_admin/register.ex
- lib/ex_admin/render.ex
Could we consider changing the API to `menu false`, so that it's consistent with other ExAdmin functions?
> Menu should support :none for registered resources

- lib/ex_admin/query.ex
Prevent "no function clause matching in Keyword.get/3" error.
> fix Keyword.get/3 no funcclause error

- lib/ex_admin/table.ex
**Issue:**
When displaying a table with a :map field with nil value, a  500 HTTP code is returned.
The exception is
```(Protocol.UndefinedError) protocol Enumerable not implemented for nil```
**Expected:**
Returns a 200 HTTP code with a proper display.
**Fix:**
Fix was to set the field value to an empty list when nil to allow proper rendering.
> Fix #283 : nil value for :map datatype

- lib/ex_admin/index.ex
- lib/ex_admin/themes/active_admin/index.ex
- lib/ex_admin/themes/admin_lte2/index.ex
- test/helpers_test.exs
- web/controllers/admin_resource_controller.ex
- web/templates/admin_resource/destroy.js.eex
**Issue:**
pagination block with page counter will not be updated after entity destroy
**How to reproduce:**
- create some entities
- follow to entities index
- note Displaing entities 1 - N of M under entity table
- remove entity
**Expected:**
- counters will decrease after destroying entity
**Actual:**
- counters stays the same as before
> Fixed pagination block update after entity delete

- lib/ex_admin/form.ex
I added microseconds support to timepicker.
But I have small problem: microsecond having range from 0 to 999 999 and I cannot render one million options for select. Text input also not suitable. Any ideas?
Also I fix bug with incorrect datetime picker
> Add microseconds to datetime picker

- mix.exs
Hound is only required for Integration Tests. It should not be required for Prod.
> Require Hound only in Test Env

- lib/ex_admin/form.ex
- test/form_test.exs
Motivation:
- This pr add some intelligence to the form build dsl and assumes that
when a collection is not passed the form should call all on the
supplied model name.
enhancement #95
> Default Collection for Checkboxes

- README.md
config must be adjusted with new namespacing, when used with phoenix >= 1.3.0
> added phoenix >= 1.3.0 config hint to README.md

- lib/ex_admin/filter.ex
- lib/ex_admin/register.ex
- lib/ex_admin/themes/active_admin/filter.ex
- lib/ex_admin/themes/admin_lte2/filter.ex
- test/filter_test.exs
- test/index_test.exs
- test/support/admin_resources.exs
- test/themes/filter_test.exs
OK, finally refactored the API, and updated all tests to pass. New API for labels:
`filter [:name, email: [label: "EMail Address"]]`
API example for ordering a `belongs_to` association:
`filter [post: [order_by: [asc: :name]]]`
I spent a lot of time thinking about this, and I ended up removing `:only` and `:except` as options. A few reasons:
1. `:only` is basically useless. If you have an explicit list of filters, wrapping it in an `:only` keyword doesn't do anything but add extra code. Since this refactor breaks backwards compatibility, I figured we might as well kill it off.
2. `:except` - this one is a little trickier to justify, but in the end I'd rather take a principled approach of having to explicitly specify which filters you want to enable for a particular screen. If we leave …
> Refactored filter API

- web/templates/layout/active_admin.html.eex
- web/templates/layout/admin_lte2.html.eex
If a consumer application uses an external `static_url` in its Phoenix.Endpoint configuration (to e.g. move all static assets served from `priv/static/` to a CDN), all calls to the `static_path` helper must be replaced with calls to the `static_url` helper to benefit from this.
> Use static_url instead of static_path

- README.md
- lib/ex_admin/helpers.ex
- lib/ex_admin/utils.ex
- test/controller_test.exs
- test/helpers_test.exs
- test/support/schema.exs
This allows using different schemas for saving and loading data. My specific use case is wanting a create form to have extra fields that get saved in associated records. For example, when I create an order in the database, I want to use the CreateOrder module, which also creates line items. For the most part you can do this by overriding the controller action, but when you have validation errors, you need to pass that changeset into the form builder, which then generates the form with the wrong path (/admin/create_orders rather than /admin/orders). I wasn't really sure where to document this, can you point me in the right direction?
> Allow overriding model_name

- web/controllers/admin_resource_controller.ex
Make batch operations for UUIDs (binary_id) work.
> Fixes #351: enable batch actions with UUIDs

- lib/ex_admin/form.ex
- test/form_test.exs
Add support for `:prompt` options in form inputs.
This will allow to have an extra option in the select with an empty value and the label specified after `prompt:`
Usage:
```elixir
input user, :inserted_at, options: [year: [prompt: "Year"], month: [prompt: "Month"], day: [prompt: "Day"]]
```
> Add support for prompt in date type.

- test/controller/errors_helper_test.exs
- web/ex_admin/errors_helper.ex
Before when the schema contained a field which was translated to an
Elixir struct the flatten_errors function would treat it as a Map and
try to map over its elements, and that would raise `Protocol.UndefinedError`.
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.Date<2017-06-08>
stacktrace:
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) lib/enum.ex:116: Enumerable.reduce/3
(elixir) lib/enum.ex:1767: Enum.map/2
(elixir) lib/enum.ex:1233: anonymous fn/3 in Enum.map/2
(stdlib) lists.erl:1263: :lists.foldl/3
(elixir) lib/enum.ex:1772: Enum.map/2
(ex_admin) web/ex_admin/errors_helper.ex:36: ExAdmin.ErrorsHelper.flatten_errors/3
(ex_admin) web/ex_admin/errors_helper.ex:29: ExAdmin.ErrorsHelper.create_errors/2
```
> Fix exception on ExAdmin.ErrorsHelper.flatten_errors/3

- lib/ex_admin/form.ex
- lib/ex_admin/table.ex
- lib/ex_admin/themes/active_admin/filter.ex
- lib/ex_admin/themes/admin_lte2/filter.ex
- test/form_test.exs
- test/themes/filter_test.exs
- web/ex_admin/errors_helper.ex
Other than adding to build_control in form.ex , in the Elixir DateTime types there is the `:minute` keyword instead of `:min` like in the Ecto.DateTime types. So I added a function to the time_value functions.
No sure though, if there are more parts that need to change.
> Support Elixir.DateTime, NaiveDateTime and Elixir.Date and Time types

- mix.exs
cherry pick from master
on elixir 1.5
the following warnings occurred
```
==> ex_admin
warning: the dependency :phoenix_html is duplicated at the top level, please remove one of them
warning: the dependency :phoenix_html is duplicated at the top level, please remove one of them
```
> Remove duplicate phoenix_html dependency

- web/controllers/admin_association_controller.ex
- web/static/js/active_admin/lib/sortable_associations.js
The current code in `sortable_associations.js` assumes `id` columns have `\d+` contents. This breaks when using Ecto schemas with `:binary_id`-typed ID columns.
This PR expands the match pattern to (loosely) match hexadecimal-encoded UUIDs as well as natural numbers, using `[-0-9a-f]+`. It also tightens the match pattern with beginning/end guards.
Depends on #344.
> Permit ID columns in sortable tables to use the Ecto :binary_id (i.e. UUID) type
