smpallen99/ex_admin

web/templates/layout/admin.html.eex

jquery-ujs.js need "data-csrf" attribute when "data-method" attribute is set to "delete".

fix invalid CSRF token problem when logout.

---

web/templates/layout/admin.html.eex

Increased the copyright year.

---

lib/mix/tasks/admin.gen.resource.ex

Sorry, I don't know if one pull request can handle changes in two branches, so creating another one PR for 0.7.3(which is actual for me).

Change file naming in generator(0.7.3)

---

lib/ex_admin/form.ex

Small fix when not displaying collection as checkboxes

---

lib/ex_admin/csv.ex
lib/ex_admin/view.ex
web/controllers/admin_resource_controller.ex

Fix csv export missing one row issue.

---

README.md

Just confused me for a moment. Great project! :)

readme example app is consistently named MyProject, not Survey

---

priv/gettext/ru_RU/LC_MESSAGES/default.po

In reference to #136 and #161 , adding russian locale.

Create russian locale

---

lib/ex_admin/index.ex

In some cases you don't want default `actions` column and you don't want to name your replacement as "Actions", or you don't want `actions` column at all.
For all these cases you could now put `actions false` into `index` macro to disable autogeneration of actions column.

Ability to completely disable actions column on index_view

---

lib/ex_admin/table.ex

I'm not sure, that I got reasoning of all clauses. But they are really look overwhelmed.
So, please, review new version of `build_th`.
Btw, it fixes #201

Refactoring of build_th. 

---

lib/ex_admin/table.ex

Reverts smpallen99/ex_admin#215
This pull request does not pass all tests

Revert "Refactoring of build_th. "

---

lib/ex_admin/themes/active_admin/index.ex
lib/ex_admin/themes/admin_lte2/index.ex
test/helpers_test.exs

New PR (since the old one was automatically closed when I recreated the branch). Refer to PR #253

Add tooltip for the index action links

---

README.md

Add missing syntax highlighting to README

---

lib/ex_admin/form.ex

Thanks for the awesome project!

Fix typo in docs

---

lib/ex_admin/index.ex
lib/ex_admin/table.ex
priv/gettext/default.pot
priv/gettext/fr_FR/LC_MESSAGES/default.po
priv/gettext/ru_RU/LC_MESSAGES/default.po
priv/gettext/uk_UA/LC_MESSAGES/default.po
test/table_test.exs
web/templates/themes/admin_lte2/layout/header.html.eex

- Added uk_UA locale and improved existing.
- Fixed building of table header (ExAdmin.Table.build_th). (It didn't work when label has utf-8 chars). Also, fixed tests for this feature.
- Small improvements in the header template.

Improve localization

---

web/web.ex

Fixes #267 
Ecto.Model was removed in Ecto 2.1

Remove usage of Ecto.Model

---

lib/ex_admin/helpers.ex

Use Phoenix.HTML.safe_to_string() to build contents

---

.gitignore
lib/ex_admin/helpers.ex
lib/ex_admin/table.ex
test/index_test.exs
test/support/schema.exs

Motivation:
- Fix issue fixes #290
Changes:
- classes with ?'s are breaking the html so I am removing them.

Fix issue with ? in class names

---

lib/ex_admin.ex
web/templates/layout/active_admin.html.eex
web/templates/layout/admin_lte2.html.eex
web/views/layout_view.ex

Addresses issue #272, and also permanently fixes the end year in the copyright.

Accept footer configuration option, or revert to default

---

lib/ex_admin/themes/active_admin/filter.ex
lib/ex_admin/themes/admin_lte2/filter.ex

Fixed build_filter bug with NaiveDateTime

---

web/templates/layout/active_admin.html.eex
web/templates/layout/admin_lte2.html.eex
web/views/layout_view.ex

Whoops :)
(Cleaner template file as well)

Footer content should pass through raw()

---

lib/ex_admin/helpers.ex
web/controllers/admin_resource_controller.ex

Pretty self explanatory I think. I didn't see a test for this feature and wasn't sure how you would want to go about testing it, but I'm happy to add a test if you point me in the right direction.

Fix index page delete fade out

---

web/controllers/admin_resource_controller.ex

Declaring changeset based on new Ecto format

---

test/controller/errors_helper_test.exs
web/ex_admin/errors_helper.ex

Apply fix to phx-1.3 branch, too.

Fix exception on ExAdmin.ErrorsHelper.flatten_errors/3

---

test/custom_changeset.exs
test/support/admin_resources.exs
test/support/schema.exs

- Create tests that show the issue reported by @whitepaperclip
@whitepaperclip, does this properly recreate the issue you reported in #278?

[WIP]: Fix changeset regression
